//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.06 at 02:27:10 PM GMT 
//


package com.appian.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anyCDTs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="anyCDTs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userDefinedTableType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="storedProcedure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="anyCDT" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "anyCDTs", propOrder = {
    "userDefinedTableType",
    "storedProcedure",
    "anyCDT"
})
public class AnyCDTs {

    @XmlElement(required = true, nillable = true)
    protected String userDefinedTableType;
    @XmlElement(required = true, nillable = true)
    protected String storedProcedure;
    @XmlElement(required = true, nillable = true)
    protected Object anyCDT;

    /**
     * Gets the value of the userDefinedTableType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDefinedTableType() {
        return userDefinedTableType;
    }

    /**
     * Sets the value of the userDefinedTableType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDefinedTableType(String value) {
        this.userDefinedTableType = value;
    }

    /**
     * Gets the value of the storedProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoredProcedure() {
        return storedProcedure;
    }

    /**
     * Sets the value of the storedProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoredProcedure(String value) {
        this.storedProcedure = value;
    }

    /**
     * Gets the value of the anyCDT property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAnyCDT() {
        return anyCDT;
    }

    /**
     * Sets the value of the anyCDT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAnyCDT(Object value) {
        this.anyCDT = value;
    }

}
